[project]
name = "python-boilerplate-github-io"
version = "0.1.0"
description = "A repository for organization documentation "
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
doc = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
]
